name: Node.js CI

on: [push, pull_request]

jobs:
  check-codestyle:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16.x']  

    steps:
    - uses: actions/checkout@v2  

    - name: Setup Node.js
      uses: actions/setup-node@v3 
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Set permissions for ESLint
      run: chmod +x ./node_modules/.bin/eslint

    - name: Check code style
      run: npm run codestyle
      env:
        CI: true